ABBREVIATIONS =["sec.",
                "secs.",
                "Sec.",
                "Secs.",
                "fig.",
                "figs.",
                "Fig.",
                "Figs.",
                "eq.",
                "eqs.",
                "Eq.",
                "Eqs.",
                "no.",
                "nos.",
                "No.",
                "Nos.",
                "al."]